HardPedia/Controllers/CategoryController.cs
using Microsoft.AspNetCore.Mvc;
using HardPedia.Data;
using HardPedia.Models.Domain;
using Microsoft.EntityFrameworkCore;

namespace HardPedia.Controllers;

public class CategoryController : Controller
{
    private readonly ApplicationDbContext _context;

    public CategoryController(ApplicationDbContext context)
    {
        _context = context;
    }

    public IActionResult Index()
    {
        var categories = _context.Categories.Include(c => c.Subjects).ToList();
        return View(categories);
    }

    [HttpGet]
    public IActionResult Search(string query)
    {
        if (string.IsNullOrEmpty(query))
        {
            return PartialView("_CategoryListPartial", (List<Category>?)_context.Categories.Include(c => c.Subjects).ToList());
        }

        // Search for categories
        var categories = _context.Categories
            .Where(c => c.Name.Contains(query) || c.Description.Contains(query))
            .Include(c => c.Subjects)
            .ToList();

        if (!categories.Any())
        {
            
            var subjects = _context.Subjects
                .Where(s => s.Title.Contains(query) || s.Content.Contains(query))
                .Include(s => s.Categories)
                .ToList();

            if (!subjects.Any())
            {
                return NotFound();
            }

            categories = subjects.SelectMany(s => s.Categories).Distinct().ToList();
        }

        return PartialView("_CategoryListPartial", categories);
    }

    [HttpGet]
    public IActionResult AddCategory()
    {
        return View();
    }


    [HttpPost]
    public IActionResult AddCategory(Category category)
    {
        if (ModelState.IsValid)
        {
            category.Id = Guid.NewGuid();
            _context.Categories.Add(category);
            _context.SaveChanges();
            return RedirectToAction("Index", "Home");
        }
        return View(category);
    }

    [HttpGet]
    public IActionResult EditCategory(Guid id)
    {
        var category = _context.Categories.FirstOrDefault(c => c.Id == id);
        if (category == null)
        {
            return NotFound();
        }
        return View(category);
    }

    [HttpPost]
    public IActionResult UpdateCategory(Guid id, Category category)
    {
        if (id != category.Id)
        {
            return NotFound();
        }

        if (ModelState.IsValid)
        {
            try
            {
                _context.Update(category);
                _context.SaveChanges();
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!_context.Categories.Any(c => c.Id == id))
                {
                    return NotFound();
                }
                else
                {
                    throw;
                }
            }
            return RedirectToAction("Index", "Home");
        }
        return View(category);
    }

    [HttpGet]
    public IActionResult DeleteCategory(Guid id)
    {
        var category = _context.Categories.FirstOrDefault(c => c.Id == id);
        if (category == null)
        {
            return NotFound();
        }

        _context.Categories.Remove(category);
        _context.SaveChanges();

        return RedirectToAction("Index", "Home");
    }

    [HttpGet]
    public IActionResult GetSubject(Guid categoryId, Guid currentSubjectId, string direction)
    {
        var category = _context.Categories
            .Include(c => c.Subjects)
            .FirstOrDefault(c => c.Id == categoryId);

        if (category == null)
        {
            return NotFound();
        }

        var subjects = category.Subjects.OrderByDescending(s => s.CreatedOn).ToList();
        var currentIndex = subjects.FindIndex(s => s.Id == currentSubjectId);

        int newIndex;
        if (direction == "next")
        {
            newIndex = (currentIndex - 1 + subjects.Count) % subjects.Count; 
        }
        else if (direction == "previous")
        {
            newIndex = (currentIndex + 1) % subjects.Count;
        }
        else
        {
            return BadRequest("Invalid direction");
        }

        var newSubject = subjects[newIndex];
        return Json(new
        {
            id = newSubject.Id,
            title = newSubject.Title,
            shortContent = newSubject.GetShortContent()
        });
    }

}

HardPedia/Controllers/UsersController.cs
using HardPedia.Data;
using HardPedia.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;

namespace HardPedia.Controllers
{
    [Authorize(Roles = "Admin")]
    public class UsersController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        private readonly ApplicationDbContext _context;

        public UsersController(ILogger<HomeController> logger, ApplicationDbContext appContext)
        {
            _logger = logger;
            _context = appContext;
        }

        

        public IActionResult ListUsers()
        {   
            List<IdentityUser> users = _context.Users.ToList();
            return View(users);
        }

        // edit a user
        public IActionResult EditUser(string id)
        {
            IdentityUser user = _context.Users.Find(id);
            if (user == null)
            {
                   return NotFound();
            }

            var userRole = _context.UserRoles.FirstOrDefault(ur => ur.UserId == user.Id);
            var role = _context.Roles.Find(userRole.RoleId);
            
            if (role == null)
            {
                   return NotFound();
            }

            var userDTO = new UserDTO(user.Id, user.UserName, user.Email, user.PhoneNumber, role.Name);
            var roles = _context.Roles.Select(categorie => new SelectListItem { Text = categorie.Name, Value = categorie.Name }).ToList();
            
            ViewBag.roles = roles;

            return View(userDTO);
        }

        [HttpPost]
        public IActionResult EditUser(UserDTO user)
        {
            var updatedUser = _context.Users.Find(user.Id);
            updatedUser.UserName = user.UserName;
            updatedUser.NormalizedUserName = user.UserName.ToUpper();
            updatedUser.Email = user.Email;
            updatedUser.NormalizedEmail = user.Email.ToUpper();
            updatedUser.PhoneNumber = user.PhoneNumber;

            
            var roleId = _context.Roles.FirstOrDefault(r => r.Name == user.Role).Id;
            var oldUserInRole = _context.UserRoles.FirstOrDefault(ur => ur.UserId == user.Id);

            var newUserInRole = new IdentityUserRole<string>
            {
                UserId = user.Id,
                RoleId = roleId
            };

            _context.UserRoles.Remove(oldUserInRole);
            _context.SaveChanges();

            _context.UserRoles.Add(newUserInRole);
            _context.SaveChanges();
            
            return RedirectToAction("ListUsers");

        }

        // delete a user
        public IActionResult DeleteUser()
        {
            return View();
        }

        [HttpPost]
        public IActionResult DeleteUser(string id)
        {
            IdentityUser user = _context.Users.Find(id);
            if (user == null)
            {
                return NotFound();
            }
            Console.Out.WriteLine(id);
            _context.Users.Remove(user);
            _context.SaveChanges();
            return RedirectToAction("ListUsers");
        }


    }
}

HardPedia/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - HardPedia</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/HardPedia.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">HardPedia</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        @if (User.Identity.IsAuthenticated)
                        {
                            if (User.IsInRole("Admin"))
                            {
                                <li class="nav-item">
                                    <a class="nav-link text-white" asp-area="" asp-controller="Category" asp-action="AddCategory">Add Category</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-white" asp-area="" asp-controller="Users" asp-action="ListUsers">Users</a>
                                </li>
                            }
                        }
                        
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - HardPedia - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>